AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de Software - Mercado pago - SQS Cria usuarios
Parameters:
  NomeFila:
    Description: Nome da Fila
    Type: String
  Environment:
    Description: Environment
    Type: String
    Default: "dev"

Resources:
  MercadoPagoSQSCriaCliente:
    Type: AWS::SQS::Queue
    Properties: 
      DelaySeconds: 0
      MessageRetentionPeriod: 3600
      QueueName: !Ref NomeFila
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30
      SqsManagedSseEnabled: false
      Tags: 
      - Key: Ambiente
        Value: !Ref Environment
      - Key: Microservico
        Value: MercadoPago
      - Key: Servico
        Value: SQS